theme: jekyll-theme-primer
title: ENG-SCI 128 - Computational Solid and Structural Mechanics
description: ES 128 Course Website by Matt and Nick
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge